[project]
name = "shared"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lachie Stewart", email = "lachiestewart2003@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "python-json-logger>=4.0.0",
]

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
